module.exports = {
  CHAT: 'CHAT',
  USER_CONNECTED: 'USED_CONNECTED',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  TYPING: 'TYPING',
  VERFIY_USER: 'VERIFY_USER',
  MESSAGE_RECIEVED: 'MESSAGE_RECIEVED',
  MESSAGE_SENT: 'MESSAGE_SENT'
}